### PR TITLE
Fix `id` of right map dataset selector

### PR DESCRIPTION
**Pull request by htmlboss**
Related to #950 

This may resolve the issue of the compare mode not updating, given in `OceanNavigator.jsx` we expect the id to be either `dataset_0` or `dataset_1`.

Can't test this locally since my container is way out of date with the package updates.

## Checks
- [ ] I ran unit tests.
- [ ] I've tested the relevant changes from a user POV.

_Hint_ To run all python unit tests run the following command from the root repository directory:
```sh
bash run_python_tests.sh
```

### CODE REVIEW

**Comment by JustinElms** [comment]
Looks like that did it! Just needed to correctly update the state of dataset_1 in OceanNavigator.jsx.

**Comment by dwayne-hart** [comment]
This PR is marked as "Draft". @htmlboss is this piece of work completed or is there additional items you wish to implement?

**Comment by htmlboss** [comment]
> Looks like that did it! Just needed to correctly update the state of dataset_1 in OceanNavigator.jsx.

LOL thanks for fixing the typo. Stupid autocomplete never works.

Since you tested it, I'll say this is good to go.

**Comment by htmlboss** [comment]
> This PR is marked as "Draft". @htmlboss is this piece of work completed or is there additional items you wish to implement?

Since Justin tested it, this is good to go!.

**Review by dwayne-hart — APPROVED** [review]

**Pull request merged**
