### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by halehkh65**
votemper unit in Riops Daily and Riops Forcast datasets are changed from Celsius to Kelvin.

### CODE REVIEW

**Comment by jmunroe** [comment]
This commit seems much more than just changing the units of votemper.  Maybe we should handle all of the required merging separately before approving this commit.

**Comment by jmunroe** [comment]
Does this now resolve #371 ?

**Comment by halehkh65** [comment]
yes, with applying these changes, in navigator, we can see different colors instead of just red.

**Comment by jmunroe** [comment]
I see now. @halehkh65, could you make your pull request to the dev branch instead?

**Comment by halehkh65** [comment]
my pull request is sent to master?

**Comment by jmunroe** [comment]
Yep: "halehkh65 wants to merge 21 commits into master from dev"

**Comment by halehkh65** [comment]
excuse me James, i think some thing is wrong here, why 21?
I just had sent a pull request for 1 file.

**Comment by jmunroe** [comment]
I think it's because the pull request was to the master branch.  So all of the many changes that have accumulated on the dev branch are being included too!

**Comment by NoahGallant-MUN** [comment]
I agree with James, If the multi_point stuff in particular is in the dev branch (which it shouldn't be, the commit was reverted) then that definitely can't be merged with master, it is not ready.

**Comment by jamesprayner** [comment]
Closing this, those commits shouldn't be merged to master

**Pull request closed without merging**
