### PR TITLE
Modified the interpolation function to return a masked array when "Nearest Neighbour" is selected 

### PR DESCRIPTION
**Pull request by BaruaSourav**
## Background
Previously, when the user selected Nearest neighbor as interpolation method, then selected an area, the CSV file download feature was facing internal server error. The issue is addressed in [issue #839](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/839).

## Why did you take this approach?
At _map.py_ file the below line #446 expects _self.data_ to be a _[MaskedArray]
(https://numpy.org/devdocs/reference/maskedarray.baseclass.html#numpy.ma.MaskedArray)_. 

https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/4beef8c5aef4c00a331c2c56d01503c1bf42777a/plotting/map.py#L446

But the [resample_nearest](https://pyresample.readthedocs.io/en/stable/api/pyresample.html#pyresample.kd_tree.resample_nearest) function of _pyresample_ module returns a _numpy.ndarray_ instead at - 

https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/4beef8c5aef4c00a331c2c56d01503c1bf42777a/data/netcdf_data.py#L606

So, I just converted the resampled _ndarray_ returned from pyresample.resample_nearest to a _np.ma.MaskedArray_ using [np.ma.asarray](https://numpy.org/doc/stable/reference/generated/numpy.ma.asarray.html#numpy.ma.asarray) while returning.

## Checks
- [x] I ran unit tests.
- [x] I've tested the relevant changes from a user POV.

_Hint_ To run all python unit tests run the following command from the root repository directory:
```sh
bash run_python_tests.sh
```

### CODE REVIEW

**Comment by dwayne-hart** [comment]
Is there a way to change the nprocs=8 to a setting in the oceannavigator.cfg file? Or should a setting of 1 or 2 be used instead?

**Comment by BaruaSourav** [comment]
@dwayne-hart The way it is done now, it doesn't get the value from the config file. But good point. @htmlboss, can we fetch a value from the oceannavigator.cfg file and use it as the value for _nprocs_ parameter here? I will take a look now.

**Comment by JustinElms** [comment]
@dwayne-hart @BaruaSourav  Doug discusses this in his analysis doc and concluded that the value of `nprocs` has no effect on Navigator performance but suggests that we remove this argument to cleanup the code a bit.

**Comment by BaruaSourav** [comment]
Okay, I think we should wait for @htmlboss to have a look at it.

**Review by htmlboss — APPROVED** [review]
Looks good! About the nprocs thing, I'd say it's safe to delete that. Dwayne's suggestion about making these things configurable is exactly what I've been thinking about for a while....maybe not for this use case since it seems to have no effect, but we should make better use of config files/environment variables over hard-coding things. It'll gave Dwayne a way easier time with fine tuning things depending on the hardware we're running on.

**Comment by BaruaSourav** [comment]
I have removed the nprocs argument from the resampling functions that we are using from pyresample module. I also agree that using environment variables/config settings instead of using a hard coded value for places where it effects the performance, is a better idea to facilitate the independence of tuning this setting while deploying on different hardware.

**Review by dwayne-hart — APPROVED** [review]

**Pull request merged**
