### PR TITLE
Creation of a new spec file for the navigator python virtual environment

### PR DESCRIPTION
**Pull request by dwayne-hart**
[Issue 762](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/762) was created by @douglatornell. The following steps were done to update matplotlib from v3.1.0 to v3.3.2.

In order to update matplotlib and matplotlib-base. An update to conda was first needed to be done. Below will be two sections containing what was updated during this process;
    
* Update available for conda
  
The following NEW packages will be INSTALLED:

    brotlipy           pkgs/main/linux-64::brotlipy-0.7.0-py38h7b6447c_1000

The following packages will be UPDATED:

      ca-certificates                                2020.1.1-0 --> 2020.7.22-0
      certifi                                 2020.4.5.1-py38_0 --> 2020.6.20-py38_0
      cffi                                1.14.0-py38he30daa8_1 --> 1.14.3-py38he30daa8_0
      conda                                        4.8.3-py38_0 --> 4.8.5-py38_0
      cryptography                         2.9.2-py38h1ba5d50_0 --> 3.1.1-py38h1ba5d50_0
      idna                                             2.9-py_1 --> 2.10-py_0
      libedit                           3.1.20181209-hc058e9b_0 --> 3.1.20191231-h14c3975_1
      libffi                                     3.3-he6710b0_1 --> 3.3-he6710b0_2
      openssl                                 1.1.1g-h7b6447c_0 --> 1.1.1h-h7b6447c_0
      pip                                         20.0.2-py38_3 --> 20.2.2-py38_0
      pycparser                                       2.20-py_0 --> 2.20-py_2
      pyopenssl          pkgs/main/linux-64::pyopenssl-19.1.0-~ --> pkgs/main/noarch::pyopenssl-19.1.0-py_1
      requests           pkgs/main/linux-64::requests-2.23.0-p~ --> pkgs/main/noarch::requests-2.24.0-py_0
      ruamel_yaml                        0.15.87-py38h7b6447c_0 --> 0.15.87-py38h7b6447c_1
      setuptools                                  46.4.0-py38_0 --> 49.6.0-py38_1
      six                 pkgs/main/linux-64::six-1.14.0-py38_0 --> pkgs/main/noarch::six-1.15.0-py_0
      sqlite                                  3.31.1-h62c20be_1 --> 3.33.0-h62c20be_0
      tk                                       8.6.8-hbc83047_0 --> 8.6.10-hbc83047_0
      tqdm                                          4.46.0-py_0 --> 4.49.0-py_0
      urllib3            pkgs/main/linux-64::urllib3-1.25.8-py~ --> pkgs/main/noarch::urllib3-1.25.10-py_0
      wheel              pkgs/main/linux-64::wheel-0.34.2-py38~ --> pkgs/main/noarch::wheel-0.35.1-py_0
      yaml                                     0.1.7-had09818_2 --> 0.2.5-h7b6447c_0

* Update for matplotlib and matplotlib-base; 

The following packages will be UPDATED:

      matplotlib             <unknown>::matplotlib-3.1.0-py36_1 --> conda-forge::matplotlib-3.3.2-0
      matplotlib-base    <unknown>::matplotlib-base-3.1.0-py36~ --> conda-forge::matplotlib-base-3.3.2-py36h5ffbc53_0
      pillow             <unknown>::pillow-6.0.0-py36he7afcd5_0 --> conda-forge::pillow-6.2.1-py36h6b7be26_0
      tk                      <unknown>::tk-8.6.9-hed695b0_1002 --> conda-forge::tk-8.6.10-hed695b0_0

### CODE REVIEW

**Comment by dwayne-hart** [comment]
An issue was found trying to launch the gunicorn WSGI web server;

    Traceback (most recent call last):
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/bin/gunicorn", line 11, in <module>
        sys.exit(run())
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
        WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
        super().run()
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
        Arbiter(self).run()
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 58, in __init__
        self.setup(app)
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/arbiter.py", line 118, in setup
        self.app.wsgi()
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
        self.callable = self.load()
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
        return self.load_wsgiapp()
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
        return util.import_app(self.app_uri)
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/gunicorn/util.py", line 411, in import_app
        app = app(*args, **kwargs)
      File "/home/ubuntu/Ocean-Data-Map-Project/oceannavigator/__init__.py", line 35, in create_app
        config_blueprints(app)
      File "/home/ubuntu/Ocean-Data-Map-Project/oceannavigator/__init__.py", line 13, in config_blueprints
        from routes.api_v1_0 import bp_v1_0
      File "/home/ubuntu/Ocean-Data-Map-Project/routes/api_v1_0.py", line 20, in <module>
        import plotting.scale
      File "/home/ubuntu/Ocean-Data-Map-Project/plotting/scale.py", line 10, in <module>
        from plotting.utils import normalize_scale
      File "/home/ubuntu/Ocean-Data-Map-Project/plotting/utils.py", line 5, in <module>
        from mpl_toolkits.basemap import Basemap
      File "/home/ubuntu/tools/miniconda/3/amd64/envs/navigator/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 26, in <module>
        from matplotlib.cbook import dedent
    ImportError: cannot import name 'dedent'

I am trying to update basemap and basemap-data-hires. However, it appears that we may be heading down a rabbit hole needing the entire navigator virtual python updated. At this time we do not have the resources to take this on. It may be best to freeze this request until we have a plan to split the UI frontend from the python compute / logic layer.

**Comment by douglatornell** [comment]
@dwayne-hart I didn't intend for `matplotlib` to be updated to a new version, just `basemap`. Is it not possible to do `conda update basemap` to get it to v1.2.2 without it triggering a `matplotlib` update? I absolutely agree that jumping `matplotlib` from 3.1.0 to 3.3.2 is *major* and not something we want to do at the moment.

The traceback you are seeing is the one I expect when `basemap<1.2.2` is run with `matplotlib>3.3.0`. We for sure want to avoid that.

**Comment by dwayne-hart** [comment]
Hey @douglatornell, greatly appreciate the offer of support. I've tried implementing the update through a different approach. At present, I still finding conflicts;

    (navigator-toolchain) [arch@8a086e34a220 ~]$ conda install -c anaconda basemap==1.3.0
    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: |
    Found conflicts! Looking for incompatible packages.

Hopefully I can capture the entire output from my terminal session for analysis and have a chat tomorrow? What is your schedule for tomorrow morning your time zone.

**Comment by douglatornell** [comment]
HI @dwayne-hart . I hate it when I see conda do that! One suggestion that might work better is 

`conda install -c conda-forge basemap==1.2.2`

I don't think that the 1.3.0 verison package is legit because there is no release with that version number mentioned anywhere in the basemap GitHub repo. Maybe someone made a typo in the recipe on the anaconda channel. The conda-forge channel has PR review and CI, so I have good confidence in it.

Even so, it is still possible that `conda install -c conda-forge basemap==1.2.2` will trigger an update cascade that will block us.

I have meetings tomorrow at 10:00-11:00 and 12:00 to 12:30 Pacific, so we could talk at 09:00 Pacific, or 11:00 Pacific - your choice.

**Comment by dwayne-hart** [comment]
Hey @douglatornell, I was looking  at the [https://anaconda.org/anaconda/basemap](anaconda.org) page and saw that for linux64 they had v1.3.0 listed. If it is a version bump to go to 1.2.2 we should be in good standing and I'll go about setting up a test python virtual environment. I'll still see what happens with going with a more up to date version in parallel. Let me send a teams invite so that I have it on my scheduler.

**Comment by dwayne-hart** [comment]
You know it is going to be an interesting journey when you encounter the following;

image

**Comment by douglatornell** [comment]
Yikes! I very much doubt that will end well.

I think your initial assessment that we are blocked on this was correct.

**Comment by dwayne-hart** [comment]
The search for a solution to updating basemap via conda-forge finally completed. It took over 72 hours and there was no clear path as the conda update / install application failed to find one.

image

As discussed with @douglatornell this past Friday. This issue will be back burnered for the time being.

**Comment by VanessaSutton-Pande** [comment]
We should hide the derived variables:
Heat Capacity
Adiabatic Temperature Gradient
Nitrogen saturation
oxygen saturation

**Pull request closed without merging**
