### PR TITLE
Update class4 index pickle generator script

### PR DESCRIPTION
**Pull request by douglatornell**
## Background
Issue #757 and issue #785 are both a result of the the `scripts/generate_class4_list.py` script being old and out of sync with the way Class 4 files are now stored in data `/data/class4/` directory tree. This PR fixes that script, and modernizes its code and some related code in `data/class4.py`.

## Why did you take this approach?
Class 4 indexing needed to be fixed, and modernizing old code is a good thing to do.

## Anything in particular that should be highlighted?
This PR includes sorting of the Class 4 files going into the index pickle such that the Class 4 date picker in the UI will have its default date set to that of the most recent available GIOPS Class 4 profiles file instead of a random date in the index.

Class 4 files prior to 2016-01-01 appear to be stored in encrypted tarballs like `/data/class4/2015/20151231/class4_20151231_GIOPS_CONCEPTS_1.1_profile.nc.gz.enc`. If those files were unpacked it is likely that `scripts/generate_class4_list.py` would be able to index them too.

## Screenshot(s)
N/A

## Checks
- [x] I ran unit tests.
- [x] I've tested the relevant changes from a user POV.

_Hint_ To run all python unit tests run the following command from the root repository directory:
```sh
bash run_python_tests.sh
```

### CODE REVIEW

**Comment by dwayne-hart** [comment]
Just an FYI @douglatornell. The system is showing that the branch is out-of-date with the base branch.

**Comment by douglatornell** [comment]
> Just an FYI @douglatornell. The system is showing that the branch is out-of-date with the base branch.

Thanks, @dwayne-hart. My dev branches seem to have gotten a bit tangled. Once @nsoontie has a chance to review/approve #799 and it gets merged, I'll get my for up to date and rebase this branch to get it current.

**Review by dwayne-hart — APPROVED** [review]
Looks good Doug.

**Review by dwayne-hart — COMMENTED** [review]
Any possible time line on will this will be rebased or updated?

**Comment by douglatornell** [comment]
Branch is up to date now, @dwayne-hart , and ready for merge.

**Review by dwayne-hart — APPROVED** [review]

**Pull request merged**
