### PR TITLE
Update to the information available to end users

### PR DESCRIPTION
**Pull request by dwayne-hart**
Adding in unique dataset help files which cut down on the help sections stored in the datasetconfig.json file.

### CODE REVIEW

**Comment by dwayne-hart** [comment]
Implemented requested changes.

**Comment by nsoontie** [comment]
Looks great Dwayne! I suppose there will be a parallel pull request in the configs repo?

**Comment by dwayne-hart** [comment]
Hi Nancy,

There will be an update to both the main and off-site branches. I just want
to ensure that the naming convention is agreed upon to minimize the number
of commits to git. But I'm open to suggestions.

Best,
Dwayne

**Comment by nsoontie** [comment]
Sounds good. Let's wait for the other changes.

**Pull request merged**
