### PR TITLE
Improved Sub-Surface Channel Detection

### PR DESCRIPTION
**Pull request by NoahGallant-MUN**
This pull requests implements thresholding and greater extrema comparison to improve the accuracy of sub surface sound channels. 

In particular this PR significantly reduces false positives.

This also adds a fix to the depth excess calculation. Some coordinates were being set to random values.

### CODE REVIEW

**Comment by htmlboss** [comment]
Could you check your .gitignore because it seems like some `node_module` folders snuck in here 😆

**Comment by NoahGallant-MUN** [comment]
This whole merge is kinda messed up now that I look at it again. I'll fix it tomorrow

**Comment by NoahGallant-MUN** [comment]
> Could you check your .gitignore because it seems like some `node_module` folders snuck in here 
> 
> Oh and I think it looks like some of the new ui code is in here too.

I fixed this PR. I was trying to merge this branch into my new UI code, but it did the opposite and I didn't notice.

**Comment by NoahGallant-MUN** [comment]
> Do we need to modify any unit tests?

Yes, forgot about that.
I've updated the SSCP tests so everything is working again.

**Pull request merged**
