### PR TITLE
Add Sentry integration for backend via Flask app

### PR DESCRIPTION
**Pull request by douglatornell**
## Background
This is the setup required to facilitate capture and analysis of Python exceptions by Sentry. It is enabled in a container by providing an environment variable named `SENTRY_DSN` whose value is a URL generated by Sentry for the "project" on their service that is to receive the data. If the envvar is absent or empty, the Sentry integration does nothing. So, it is safe to have this code in the codebase that is used for dev or any deployment.

## Why did you take this approach?
It's the documented way to do it: https://docs.sentry.io/platforms/python/guides/flask/

## Anything in particular that should be highlighted?
TODOs before this can go live:
- [x] Add the `sentry-sdk` and `blinker`[1] packages to the conda env config. `conda install -c conda-forge sentry-sdk blinker` did the job in my dev container on `dory`. It installed `sentry=0.19.1` and `blinker=1.4` and updated `certifi` to `2020.06.20`. @dwayne-hart do you mind doing the the conda environment and spec-file changes for this? I think you have a process for those kind of changes that I would likely mess up if I were to do them. Your choice whether you do a separate PR, or commit the changes in this branch.

  [1] `blinker` (https://pythonhosted.org/blinker/) is used by the Flask signal component that `sentry-sdk` hooks into.

- [x] Chose a name for the Sentry project that we want to capture exception data from https://navigator.oceansdata.ca/public/ in. `navigator-prod` maybe? Opinions @dwayne-hart and @htmlboss ?  _Decided on `public-prod`_.

- [x] Once we have a Sentry project name I will set it up and that will generate the DSN URL that will enable data capture. _See https://sentry.io/settings/dfo-ocean-navigator/projects/public-prod/keys/_

- [x] Figure out how to ensure that the `SENTRY_DSN` envvar is always set for the https://navigator.oceansdata.ca/public/ container while keeping the DSN URL secret (i.e. not committed). Ideas @dwayne-hart ?

- [ ] Deploy

- [x] Profit!? :grin: 

## Screenshot(s)
N/A

## Checks
- [x] I ran unit tests.
- [x] I've tested the relevant changes from a user POV.

_Hint_ To run all python unit tests run the following command from the root repository directory:
```sh
bash run_python_tests.sh
```

### CODE REVIEW

**Comment by dwayne-hart** [comment]
@douglatornell, if we have three or more LXD/LXC containers running in production. Should we have all three or more sending messages to the same project? Is there a way to create a subproject within production for each node?

I would ask that three projects be created and called them dev, prod, bug.

**Comment by douglatornell** [comment]
> @douglatornell, if we have three or more LXD/LXC containers running in production. Should we have all three or more sending messages to the same project? 

@dwayne-hart, my initial thought is that if 3 or more containers are running the same version of the code, that would be fine. But if they are running different codebases (dev, prod, bug) things could be confusing.

> Is there a way to create a subproject within production for each node?

There is a Sentry feature called Environments that I haven't used and need to read about that might be like subproject - not sure yet.

> 
> I would ask that three projects be created and called them dev, prod, bug.

I'm thinking we do `prod` for the https://navigator.oceansdata.ca/public/ container to start with so that we can some immediate info about the exceptions that our users are triggering. We can expand to more projects/environments as we get more experience with Sentry and figure out how best to use it to improve Navigator. Does that make sense, or am I too much of an incrementalist?

So maybe Sentry project name `prod` or `public-prod`? I'm thinking about other "released production deployments" like GPSC maybe that would need an `adjective-prod` name. I really don't know enough about the deployment side though, so maybe I'm typing nonsense.

It's late there - don't feel that you have to continue this conversation tonight!

**Comment by dwayne-hart** [comment]
@douglatornell , I agree with your strategy wrt the slow roll on the prod or public-prod. Having the ability to create separate environments. Maybe we would be able to have an environment for each deployment we maintain. If we wish for others to contribute we need to reach out to the various stakeholders who maybe running their own instance if they wish to opt in. We can definitely discuss this further whenever you wish.

**Comment by dwayne-hart** [comment]
A new navigator spec file has been created #781 which has the supporting packages for sentry.io. Also, a new Ubuntu 20.04 LTS image was created to have the necessary environment variable define.

**Review by dwayne-hart — APPROVED** [review]
This work will help with understanding where things break down via sentry.io.

**Pull request merged**
