### PR TITLE
Add CHS baselayer

### PR DESCRIPTION
**Pull request by htmlboss**
## Background

wms server: https://gisp.dfo-mpo.gc.ca/arcgis/rest/services/CHS/ENC_MaritimeChartService/MapServer/exts/MaritimeChartService/WMSServer

tilewms docs: https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html

## Why did you take this approach?

Have to manipulate the z-indices of the layers so the ordering is correct depending on if the chs layer is selected or not...

## Screenshot(s)

image

image

## Checks
- [ ] I ran unit tests.
- [x] I've tested the relevant changes from a user POV.

_Hint_ To run all python unit tests run the following command from the root repository directory:
```sh
bash run_python_tests.sh
```

### CODE REVIEW

**Comment by htmlboss** [comment]
Just noticed the data tiles are being drawn on top of the CHS stuff, we'll need to adjust the order in which these things are drawn. 
image

**Comment by dwayne-hart** [comment]
Also noticed that your branch is out of date. May explain why certain
features were not working properly.

**Comment by htmlboss** [comment]
OK let's give this a spin on the staging site.

**Review by dwayne-hart — COMMENTED** [review]
Is there any additional changes that need to be made to either configuration file?

I have deployed the code on a development site and when I zoom in I do not see any of the CHS information.

image

**Comment by htmlboss** [comment]
woops...the front-end needs to be compiled, and you can select the chs baselayer in the settings tab...

**Comment by dwayne-hart** [comment]
@Nabil M <nmiri127@gmail.com> are you able to provide an example API call
that generated the graphic you had uploaded?

I currently have your branch running on oceansdata.io
<https://www.oceansdata.io>. After changing the default basemap to *Maritime
Chart Service*. I get the following rendering;

[image: image.png]

Then if I zoom into the Avalon Peninsula I get the following;

[image: image.png]

**Comment by htmlboss** [comment]
Added some z-index manipulation which should resolve the undesired artifacts.

Ready for another spin on a testing site...

**Comment by dwayne-hart** [comment]
It appears that everything is working properly.

image

image

However, on a more resource limited system issues with trying to show the St. John's harbor there exist issues.

image

**Comment by dwayne-hart** [comment]
A full deletion (code and cache), clone, build, and launch removed the unwanted behavior. The code is running as expected on two development sites.

image

**Review by dwayne-hart — APPROVED** [review]
Desired software behavior was achieved.

**Pull request merged**
