### PR TITLE
Created and updated various conda spec files

### PR DESCRIPTION
**Pull request by dwayne-hart**
Created a new conda environment called cdo-tools which contains the 
Unidata cdo applications.

Installed lftp in the devops conda environment and created an
updated spec file.

Updated the navigator spec file due in part to the following changes;
 * Installed a newer version of gunicorn (20.0.4)
 * Installed sentry-sdk and blinker for the API debugging utility
 * Installed defopt which is needed for the Observations project
 * Installed geojson as this is needed by Nabil Miri for development
   work he is undertaking.

Updated the hash signature of the configs submodule.

### CODE REVIEW

**Comment by dwayne-hart** [comment]
In order to support the work @douglatornell has undertaking in bringing sentry.io api error logging and metrics. Please refer to #776. The Miniconda toolchain has had the sentry-sdk and blinker packages installed. A new conda spec file for the navigator virtual environment was also created in order to ensure that any Ocean Navigator deployment will be able to receive not only the package artifacts but the spec file to be able to create the Miniconda toolchain from scratch.

**Review by nsoontie — COMMENTED** [review]
Thanks @dwayne-hart . It's still not clear that all of the unit tests pass under the new spec file. Can you confirm ?

Also, why is there a change to the datasetconfig.json?

**Comment by dwayne-hart** [comment]
@nsoontie , I ran the unit tests and only encountered one error pertaining to the deep sound channel work that @htmlboss is working on. 

```
======================================================================
ERROR: test_deepsoundchannel (tests.test_data_functions.TestDataFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildadm/Ocean-Data-Map-Project/tests/test_data_functions.py", line 47, in test_deepsoundchannel
    data=[0], dims=['depth']), [45], [0.5], [32]), 0)
  File "/home/buildadm/Ocean-Data-Map-Project/data/calculated_parser/functions.py", line 334, in deepsoundchannel
    data[data < 500] = np.nan
TypeError: 'numpy.int64' object does not support item assignment

----------------------------------------------------------------------
Ran 188 tests in 108.455s

FAILED (errors=1, skipped=20)

```
The entire log file captured during the test run is available  below;
[run_python_tests.log](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/files/5570228/run_python_tests.log)

**Comment by dwayne-hart** [comment]
The current `configs @ 6776814` submodule contained in the Ocean-Data-Map-Project repo is out of date. It should be `configs @ 1ce66b9`.

- [configs submodule within the Ocean-Data-Map-Project/oceannavigator directory](https://github.com/DFO-Ocean-Navigator/configurations/tree/6776814a3550f543dfc0a82ec24ad8459ef4e699)

- [configuration repo]( https://github.com/DFO-Ocean-Navigator/configurations)

**Comment by nsoontie** [comment]
@htmlboss Have you seen this failed unit test before? Any concerns?

**Review by htmlboss — APPROVED** [review]

**Pull request merged**
